" == Vundle == 
set nocompatible " Required by vundle
filetype off     " Required by vundle

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'tpope/vim-rails'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-commentary'
Plugin 'kana/vim-textobj-user'
Plugin 'nelstrom/vim-textobj-rubyblock' " depends on kana/vim-textobj-user
Plugin 'ngmy/vim-rubocop'
Plugin 'tpope/vim-surround'
Plugin 'mattn/emmet-vim'
Plugin 'fatih/vim-go'

" vim-snipmate
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'

call vundle#end()         " Required by vundle
filetype plugin indent on " Required by vundle
" == Vundle ==

" enable matchit.vim
runtime macros/matchit.vim

" == Theme Setting == 
" Set Solarized light theme
execute pathogen#infect()

syntax enable
" let g:solarized_termcolors=256 " For ubuntu to work
" set t_Co=256 " For ubuntu to work
set background=light
colorscheme solarized
" == Theme Setting == 

" Quick type letter j or k to escape
imap jk <esc>
imap kj <esc>

" Move up and down by visible lines if current line is wrapped 
nmap j gj
nmap k gk

" Use tab for autocomplete
" inoremap <Tab> <C-P>

set relativenumber
set number
set cursorline
set cursorcolumn
set expandtab
set shiftwidth=2
set softtabstop=2
set laststatus=2
set statusline=%f
set smartindent
