" == Vundle == 
set nocompatible " Required by vundle
filetype off     " Required by vundle

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'ctrlpvim/ctrlp.vim' " CtrlP Fuzzy File Finder
Plugin 'tpope/vim-rails' " Rails.vim

call vundle#end()         " Required by vundle
filetype plugin indent on " Required by vundle
" == Vundle ==

" == Theme Setting == 
" Set Solarized light theme
execute pathogen#infect()

syntax enable
set background=light
colorscheme solarized

if has('gui_running')
  set background=light
else
  set background=dark
endif
" == Theme Setting == 

" Quick type letter j or k to escape
imap jk <esc>
imap kj <esc>

" Move up and down by visible lines if current line is wrapped 
nmap j gj
nmap k gk

" Display line numbers beside buffer
set number

" Set default font size
set guifont=Monaco:h16
