# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="solarized"

plugins=(git-prompt emoji rails git-flow golang)

source $ZSH/oh-my-zsh.sh

# Load custom executable functions
for function in ~/code/dotfiles/zsh/functions/*; do
  source $function
done

# Load tat file
export PATH=$HOME/bin:$PATH

# Golang paths
export GOPATH=$HOME/gospace
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# Alias
# Start mysql server
alias mss="mysql.server start"
